version: '3'

services:
  web:
    image: httpd:2.4.41
    container_name: apache_docker
    volumes:
      - "./web:/var/www/html"                                                                 
      - "./etc/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf"                          
      - "./etc/apache/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - php
  php:
    image: php:7.2.26-fpm
    container_name: php_docker
    volumes:
      - "./web:/var/www/html"
